### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by jaredsburrows** [cbeust/dropwizard-guice#1]

**Comment by cbeust** [comment]
Uh I just uploaded this a couple of hours ago, are you stalking me? ;-)

**Comment by jaredsburrows** [comment]
@cbeust When you follow someone on Github, it comes up in the feed when they create a new repo, haha.

**Comment by cbeust** [comment]
FYI, this is just a starter project that I'm not going to modify much any
more. I converted it to a 100% Kotlin project and that one should end up
powering one of my web sites.


-- 
Cédric
